### ISSUE TITLE
Please mention 'bosh-blobstore-dav' somewhere so its easier to figure out that this repo is its source

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/bosh-davcli#3]
When debugging a `bosh-blobstore-dav -c /var/vcap/bosh/etc/blobstore-dav.json get ...` we could not figure out where `bosh-blobstore-dav` cli came from.

Ultimately figured it out from the `mv` command in stemcell builder https://github.com/cloudfoundry/bosh/blob/672b542911f6056da2ebb1558a76b3bd74f3cf00/stemcell_builder/stages/bosh_go_agent/apply.sh#L37

Could this repo please add a readme and document this relationship?

And/or can we use `bosh-davcli` instead of `bosh-blobstore-dav` in the stemcell so the CLI only has one name?

/cc @bodymindarts

**Comment by benmoss** [comment]
Yep, this is confusing for me too. Maybe even just a README for the davcli repo would give it enough SEO someone has a fighting chance of finding it.
