### ISSUE TITLE
[err] flate: read error at offset

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/bosh-davcli#4]
From bosh `Compiling package buildpack_php...` logs:

```
Running command: 'bosh-blobstore-dav -c /var/vcap/bosh/etc/blobstore-dav.json get 87a1a29c-80ad-43d6-b2b0-e89a0f1f91e7 /var/vcap/data/tmp/bosh-blobstore-externalBlobstore-Get702293311', stdout: 'Error running app - flate: read error at offset 505576626: http: unexpected EOF reading trailer'
```

Suggestions on root causes for this?

/cc @bodymindarts

**Comment by bodymindarts** [comment]
Could be related to (http.Client.Do() returning EOF error rarely but predictably)[https://groups.google.com/forum/#!topic/golang-nuts/HsaLNTMq3eI]

From the issue:
```EOF means that the socket was closed before that was expected. It often signals a dropped network connection. When I get it, it usually means that the http.Transport was reusing an old connection, and that connection got closed by the server without the Transport's connection-reuse logic noticing it.```

Looks like the issue is that the server is closing the connection unexpectedly.

**Comment by bodymindarts** [comment]
This is highly hypothetical:
Blobstore server is behind an nginx with [2 worker processes](https://github.com/cloudfoundry/bosh/blob/master/release/jobs/blobstore/templates/nginx.conf.erb#L2) but cf release specifies [6 compilation workers](https://github.com/cloudfoundry/cf-release/blob/master/templates/cf-deployment.yml#L25) could be that it has to do with the concurrent requests trying to fetch a blob that leads to the server unexpectedly close a connection.

**Comment by bodymindarts** [comment]
Could have something to do with the [nginx configuration](https://github.com/cloudfoundry/bosh/blob/master/release/jobs/blobstore/templates/nginx.conf.erb). In particular there being 2 worker processes and a 75s keepalive_timeout. With [6 compilation workers](https://github.com/cloudfoundry/cf-release/blob/master/templates/cf-deployment.yml#L25) fetching blobs perhaps the connections are timing out.

**Comment by wkielas** [comment]
Any update on the issue? This continues to affect us.
